name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebug --stacktrace
        
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Distribute to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: "qa-coordinapp"
          testers: "oscart@coordinadora.com,sdhajan@coordinadora.com,camilov@coordinadora.com"
          releaseNotes: |
            Commit: ${{ github.sha }}
            Autor:  ${{ github.actor }}
            Mensaje: ${{ github.event.head_commit.message }}
          file: app/build/outputs/apk/debug/app-debug.apk 
